# Generated by Django 4.1.7 on 2023-02-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('code', models.CharField(max_length=24)),
                ('location', models.CharField(max_length=30)),
                ('quantity', models.SmallIntegerField()),
                ('producttype', models.CharField(max_length=30)),
            ],
        ),
    ]
