# Generated by Django 4.1.7 on 2023-02-27 08:26

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(upload_to=product.models.upload_image_path),
        ),
    ]
